database_name:
  class:    Sdx_Db_Adapter_Mysql
  host:     localhost
  username: user_name
  password: password
  dbname:   database_name
  charset:  utf8
  unix_socket:   /var/lib/mysql/mysql.sock
  
board_master:
  class:    Sdx_Db_Adapter_Mysql
  host:     localhost
  username: board-admin
  password: test
  dbname:   board
  charset:  utf8
  unix_socket:   /var/lib/mysql/mysql.sock
 
board_slave:
  alias:    board_master